INCLUDE MC.LIB
.MODEL small
.STACK 100

.DATA
    NOM DB "Nombre: $"
    TITULO DB "INGENIERIA EN COMPUTACION UTM$",13,10,"$"
    TEXTO2 DB "ES ALUMNO DEL CURSO$"
    SALTA DB 13,10,"$"

ALUMNO STRUC
    NOMBRE DB 40 DUP (0)
    MATRICULA DB 20 DUP (0)
    SEMESTRE DB 5 DUP (?)
    MATERIA DB 30 DUP (?)
    ESPECIAL DB 30 DUP (?)
ALUMNO ENDS

ESTUDIANTE ALUMNO <"Jorge Elorza Velasquez$","2021020098$","4$","Lenguaje Ensamblador$","Ninio Prodigio$">


.CODE
PRINCI PROC FAR
;PROTOCOLO
push ds
sub ax,ax
push ax
MOV AX,@DATA
MOV DS,AX

Escribe_cadena2 TITULO
SALTA
SALTA
Escribe_cadena2 NOM
Escribe_cadena2 ESTUDIANTE.NOMBRE
SALTA
Escribe_cadena2 ESTUDIANTE.MATRICULA
SALTA
Escribe_cadena2 ESTUDIANTE.SEMESTRE
SALTA
Escribe_cadena2 ESTUDIANTE.MATERIA
SALTA
Escribe_cadena2 ESTUDIANTE.ESPECIAL
Sal_a_dos

PRINCI ENDP
END PRINCI