;Juego del ahorcado
INCLUDE MACRO.LIB
; DEFINICION SEGMENTO DE PILA
    PILA segment para stack 'stack'       
        DB 20 DUP (0)                   ; Define espacio en la pila
    PILA ENDS

; DEFINICION  SEGMENTO DE DATOS
DATOS SEGMENT PARA 'DATA'
    MSG1 DB 'NOMBRE: $'
    TITULO DB 'INGENIERIA EN COMPUTACION UTM',13,10,"$"
    MSG2 DB 'MATRICULA: $'
    MSG3 DB 'SEMESTRE: $'
    MSG4 DB 'MATERIA: $'
    MSG5 DB 'ALUMNO REGULAR: $ '
    SALTA DB 13,10,"$"
    
    
    ALUMNO STRUC
        NOMBRE DB 40, ?, 40 DUP ("$"), "$"
        MATRICULA DB 12, ?, 40 DUP ("$"),"$"
        SEMESTRE DB 5,?,5 DUP('$'),"$"
        MATERIA DB 40, ?, 40 DUP ("$"), "$"
        ESPECIAL DB 40, ?, 40 DUP ("$"), "$"
    ALUMNO ENDS
    
    ;ESTUDIANTE ALUMNO <'MARTINEZ LORENZO FRIDA$','2021020174$','4TO$','LENGUAJE ENSAMBLADOR$','ALUMNO REGULAR$'>
    ESTUDIANTE ALUMNO <'$','$','$','$','$'>
    
DATOS ENDS
    
; DEFINICION  SEGMENTO DE CODIGO
CODIGO SEGMENT PARA 'CODE'
  
 MAIN PROC FAR      
 ASSUME SS:PILA, DS:DATOS, CS:CODIGO
    INICIO_DL
    
    ;LEEMOS DATOS
    LIMPIAR_PANTALLA 50H
    ESCRIBE_CADENA TITULO
    SALTAR
    ESCRIBE_CADENA MSG1
    LEERCADENA ESTUDIANTE.NOMBRE
    SALTAR
    ESCRIBE_CADENA MSG2
    LEERCADENA ESTUDIANTE.MATRICULA
    SALTAR
    ESCRIBE_CADENA MSG3
    LEERCADENA ESTUDIANTE.SEMESTRE
    SALTAR
    ESCRIBE_CADENA MSG4
    LEERCADENA ESTUDIANTE.MATERIA
    SALTAR
    ESCRIBE_CADENA MSG5
    LEERCADENA ESTUDIANTE.ESPECIAL
    
    ;MOSTRARMOS DATOS
    
    LIMPIAR_PANTALLA 50H
    ESCRIBE_CADENA TITULO
    SALTAR
    ESCRIBE_CADENA MSG1
    SALTAR
    ESCRIBE_CADENA ESTUDIANTE.NOMBRE+2
    SALTAR
    ESCRIBE_CADENA ESTUDIANTE.MATRICULA+2
    SALTAR
    ESCRIBE_CADENA ESTUDIANTE.SEMESTRE+2
    SALTAR
    ESCRIBE_CADENA ESTUDIANTE.MATERIA+2
    SALTAR
    ESCRIBE_CADENA ESTUDIANTE.ESPECIAL+2
 RET
 MAIN ENDP   ;Fin proceso (FIN DEL MAIN)
 
CODIGO ENDS                 ;Fin segemento de codigo
END MAIN