;Carga de memoria los valores del dato tabla y los imprime en pantalla
;como caracteres. Uso de LODSB
STACKSG SEGMENT PARA STACK 'STACK'
DB 100H DUP(0)
STACKSG ENDS

DATASG SEGMENT PARA 'DATA'
tabla DB 1,2,3,4,5,6,7,8,9,10
conta db 10
DATASG ENDS

CODESG SEGMENT PARA 'CODE'
PRINCI PROC FAR
ASSUME SS:STACKSG, DS:DATASG, CS:CODESG
    PUSH DS
    SUB AX,AX
    PUSH AX
    MOV AX,SEG DATASG
    MOV DS,AX
    ;mov es, ax no es necesario puesto que solo ocupamos SI, NO ES NECESARIO ALINEAR DI
    
    STD
    MOV CL,0
    MOV SI, OFFSET TABLA+9
    OTRO: LODSB
    MOV DL,AL ; MOV AL,[SI], INC SI
    ADD DL,48 ; SUMA PARA CONVERTIR DE BINARIO A ASCII= 30H
    CALL ESCRIBE
    INC CL
    MOV DL,' '
    CALL ESCRIBE
    CMP CL,CONTA
    JNE OTRO
    CALL FIN
PRINCI ENDP


MENSAJE PROC
PUSH AX
MOV AH,09H
INT 21H
POP AX
RET
MENSAJE ENDP

LEE PROC
PUSH AX
MOV AH,01
INT 21H
POP AX
RET
LEE ENDP

ESCRIBE PROC
PUSH AX
MOV AH,02
INT 21H
POP AX
RET
ESCRIBE ENDP


FIN PROC
MOV AH,4CH
INT 21H
RET
FIN ENDP

CODESG ENDS
END PRINCI