; COPIA UNA SUBCADENA DE LA CADENA1 A LA 2 DIRECCION IZQ A DER CON
;MOVSW
STACKSG SEGMENT PARA STACK 'STACK'
DB 100H DUP(0)
STACKSG ENDS

DATASG SEGMENT PARA 'DATA'
CAD1 DB 'PROGRAMA QUE IMPRIME UN MENSAJE$'
CAD2 DB '                               $'
DATASG ENDS

CODESG SEGMENT PARA 'CODE'
PRINCI PROC FAR
    ASSUME SS:STACKSG, DS:DATASG, CS:CODESG
    PUSH DS
    SUB AX,AX
    PUSH AX
    MOV AX,SEG DATASG
    MOV DS,AX
    MOV ES,AX ; Linea que se a?ade para el uso de MOVS
    
    CLD ; BANDERA DE DIRECCION DE IZQ A DER
    MOV CX,15H
    ;MOV CX,10H;CUANTAS PALABRAS (2BYTES)
    LEA DI,CAD2
    LEA SI,CAD1
    REP MOVSW ;POR PALABRAS
    LEA DX,CAD2
    CALL MENSAJE
    CALL LEE
    CALL FIN
PRINCI ENDP


MENSAJE PROC
    PUSH AX
    MOV AH,09H
    INT 21H
    POP AX
    RET
MENSAJE ENDP

LEE PROC
    PUSH AX
    MOV AH,01
    INT 21H
    POP AX
    RET
LEE ENDP

FIN PROC
    MOV AH,4CH
    INT 21H
    RET
    FIN ENDP
CODESG ENDS

END PRINCI