;------------------------------------------------
;MANEJO DEL MOUSE EN MODO GRAFICO
;------------------------------------------------
.MODEL SMALL
extrn LEE:near
extrn MENSAJE: near
extrn sal_a_dos : near
EXTRN INIT_MOUSE : NEAR
EXTRN SHOW_CURSOR :NEAR
EXTRN PUT_CURSOR : NEAR
EXTRN OCULTA_MOUSE: NEAR
EXTRN GRAFICO:NEAR
.STACK 100H
.DATA
MEN1 DB 'NO MOUSE DETECTADO$'
.CODE
MAIN PROC FAR
 ; Protocolo 
 PUSH DS
 SUB AX, AX
 PUSH AX
 MOV AX, @DATA
 MOV DS, AX
 ; Protocolo (End)
 CALL GRAFICO
 ; Inicializacion del mouse 
 CALL INIT_MOUSE
 CMP AX,0000
 JE ERROR
 CALL SHOW_CURSOR
 MOV CX, 620
 MOV DX, 410
 CALL PUT_CURSOR
 JMP EXIT
ERROR: LEA DX,MEN1
 CALL MENSAJE
 CALL LEE
 JMP SALTE
EXIT: CALL LEE
 CALL OCULTA_MOUSE
SALTE: CALL RESTAURA
 CALL SAL_A_DOS
 RET
MAIN ENDP

 RESTAURA PROC
 MOV AH, 00H
 MOV AL, 03H
 INT 10H
 RET
 RESTAURA ENDP
END MAIN